FROM debian:13-slim AS build-stage

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|deb\.debian\.org|mirrors.cernet.edu.cn|g' /etc/apt/sources.list.d/debian.sources

RUN apt update && apt install -y \
    --no-install-recommends \
    python3 \
    python-is-python3 \
    build-essential \
    cmake \
    libicu-dev \
    libpng-dev \
    libcurl4-openssl-dev \
    libsqlite3-dev \
    zlib1g-dev \
    ninja-build \
    libmaxminddb-dev \
    libluajit-5.1-dev \
    git

WORKDIR /code

COPY . .

RUN mkdir dist

RUN cmake . \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=./dist \
    -GNinja

RUN cmake --build . --target install


FROM debian:13-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|deb\.debian\.org|mirrors.cernet.edu.cn|g' /etc/apt/sources.list.d/debian.sources

RUN apt update && apt install -y \
    --no-install-recommends \
    libicu76 \
    libpng16-16t64 \
    libcurl4t64 \
    libsqlite3-0 \
    zlib1g \
    libmaxminddb0 \
    libluajit-5.1-2

COPY --from=build-stage /code/dist /dist

WORKDIR /dist

CMD ["./Infclass-Server"]